const calendar = [
  {
    name: "Fall 2019",
    courses: [
    {
      "_id": "61aa57c03309bafd81a55b59",
      "courseId": "1026",
      "courseTitle": "Computer Networks I",
      "courseCode": "CPS706",
      "courseSection": "031",
      "courseDescription": "Internet, the network edge, the network core, delay, loss and throughput, protocol layers.",
      "courseCredits": "1",
      "durationHours": "60",
      "department": "Computer Science",
      "semester": "Winter",
      "year": "2022"
    },
    {
      "_id": "61aa57c03309bafd81a55b4e",
      "courseId": "1027",
      "courseTitle": "Web Applications",
      "courseCode": "CPS630",
      "courseSection": "011",
      "courseDescription": "This course is a continuation of CPS 530. Students will learn advanced techniques for designing and building web applications using modern technologies.",
      "courseCredits": "1",
      "durationHours": "60",
      "department": "Computer Science",
      "semester": "Winter",
      "year": "2022"
    },
    {
      "_id": "61aa57c03309bafd81a55b60",
      "courseId": "1028",
      "courseTitle": "Computer Graphics",
      "courseCode": "CPS511",
      "courseSection": "011",
      "courseDescription": "Software and hardware considerations in computer graphics.",
      "courseCredits": "1",
      "durationHours": "60",
      "department": "Computer Science",
      "semester": "Winter",
      "year": "2022"
    },
    {
      "_id": "61aa57c03309bafd81a55b50",
      "courseId": "1029",
      "courseTitle": "Creative Writing",
      "courseCode": "ENG505",
      "courseSection": "011",
      "courseDescription": "This upper-level course offers students the opportunity both to study models of good writing and to develop their own creative abilities. ",
      "courseCredits": "1",
      "durationHours": "60",
      "department": "English",
      "semester": "Winter",
      "year": "2022"
    },
    {
      "_id": "61aa57c03309bafd81a55b5c",
      "courseId": "1035",
      "courseTitle": "Software Tools for Startups",
      "courseCode": "CPS847",
      "courseSection": "011",
      "courseDescription": "This course will discuss core tools, frameworks, and packages used by modern startups.",
      "courseCredits": "1",
      "durationHours": "60",
      "department": "Computer Science",
      "semester": "Winter",
      "year": "2022"
    },
    ]
  },
  {
    name: "Winter 2020",
    courses: [
      {
        "_id": "61aa57c03309bafd81a55b47",
        "courseId": "1036",
        "courseTitle": "Principles of Marketing",
        "courseCode": "MKT100",
        "courseSection": "011",
        "courseDescription": "This course introduces students to the fundamental building blocks of marketing.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Marketing",
        "semester": "Winter",
        "year": "2022"
      },
      {
        "_id": "61aa57c03309bafd81a55b4f",
        "courseId": "1037",
        "courseTitle": "Geometry",
        "courseCode": "MTH540",
        "courseSection": "021",
        "courseDescription": "Projective plane and 3-space. Cross-ratio, perspectivity, conics and quadrics, poles and polars.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Mathematics",
        "semester": "Winter",
        "year": "2022"
      },
      {
        "_id": "61aa57c03309bafd81a55b5f",
        "courseId": "1038",
        "courseTitle": "Music and Film",
        "courseCode": "RTA180",
        "courseSection": "011",
        "courseDescription": "This course explores the relationship between music and film.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Media",
        "semester": "Winter",
        "year": "2022"
      },
      {
        "_id": "61aa57c03309bafd81a55b53",
        "courseId": "1039",
        "courseTitle": "The Geography of Toronto",
        "courseCode": "GEO793",
        "courseSection": "021",
        "courseDescription": "This course provides students with an understanding of Toronto, by examining interrelated historical, social, cultural, political, and environmental issues.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Geography",
        "semester": "Winter",
        "year": "2022"
      },
      {
        "_id": "61aa57c03309bafd81a55b5a",
        "courseId": "1000",
        "courseTitle": "Computer Science I",
        "courseCode": "CPS101",
        "courseSection": "011",
        "courseDescription": "This is an introduction to the basics of Computer Science",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Computer Science",
        "semester": "Fall",
        "year": "2021"
      },
    ]
  },
  {
    name: "Fall 2020",
    courses:[
  {
    "_id": "61aa57c03309bafd81a55b52",
    "courseId": "1001",
    "courseTitle": "Computer Organization I",
    "courseCode": "CPS213",
    "courseSection": "021",
    "courseDescription": "This course introduces the students to the principles and fundamentals of digital system design.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57bf3309bafd81a55b44",
    "courseId": "1002",
    "courseTitle": "Discrete Mathematics I",
    "courseCode": "MTH110",
    "courseSection": "021",
    "courseDescription": "This course covers the fundamentals of discrete mathematics with a focus on proof methods.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Mathematics",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b4b",
    "courseId": "1003",
    "courseTitle": "Physics",
    "courseCode": "PCS110",
    "courseSection": "011",
    "courseDescription": "Topics: Units and vectors. Motion - linear, projectile, circular and oscillatory motion.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Physics",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57bf3309bafd81a55b42",
    "courseId": "1004",
    "courseTitle": "The Architecture of Music",
    "courseCode": "MUS106",
    "courseSection": "011",
    "courseDescription": "this course will provide a range of technical tools for acquiring a thorough grasp of how music is organized and created.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Music",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b4d",
    "courseId": "1010",
    "courseTitle": "Communication in the Computer Industry",
    "courseCode": "CMN300",
    "courseSection": "011",
    "courseDescription": "In this workshop course, students learn to present technical information to audiences with a range of technical knowledge.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
    ]
  },
  {
    name: "Winter 2021",
    courses:[
      {
        "_id": "61aa57bf3309bafd81a55b40",
        "courseId": "1011",
        "courseTitle": "Data Structures",
        "courseCode": "CPS305",
        "courseSection": "011",
        "courseDescription": "Introduction to data structures and algorithms.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Computer Science",
        "semester": "Fall",
        "year": "2021"
      },
      {
        "_id": "61aa57c03309bafd81a55b56",
        "courseId": "1012",
        "courseTitle": "Introduction to UNIX, C and C++",
        "courseCode": "CPS393",
        "courseSection": "011",
        "courseDescription": "The course introduces the UNIX operating system, and the C and C++ languages.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Computer Science",
        "semester": "Fall",
        "year": "2021"
      },
      {
        "_id": "61aa57c03309bafd81a55b4a",
        "courseId": "1013",
        "courseTitle": "Linear Algebra",
        "courseCode": "MTH108",
        "courseSection": "011",
        "courseDescription": "Systems of linear equations, matrices determinants, vectors, geometry, linear transformations.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Mathematics",
        "semester": "Fall",
        "year": "2021"
      },
      {
        "_id": "61aa57c509b3e9d1ff4c664c",
        "courseId": "1014",
        "courseTitle": "Economic History",
        "courseCode": "ECN630",
        "courseSection": "011",
        "courseDescription": "The central focus of this course is institutions and organization and how these impacted technological change and economic growth in different periods.",
        "courseCredits": "1",
        "durationHours": "60",
        "department": "Economics",
        "semester": "Fall",
        "year": "2021"
      },
    ]
  },
]

const fulfilled_courses = [
  {
    "_id": "61aa57c03309bafd81a55b50",
    "courseId": "1029",
    "courseTitle": "Creative Writing",
    "courseCode": "ENG505",
    "courseSection": "011",
    "courseDescription": "This upper-level course offers students the opportunity both to study models of good writing and to develop their own creative abilities. ",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "English",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b5c",
    "courseId": "1035",
    "courseTitle": "Software Tools for Startups",
    "courseCode": "CPS847",
    "courseSection": "011",
    "courseDescription": "This course will discuss core tools, frameworks, and packages used by modern startups.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b47",
    "courseId": "1036",
    "courseTitle": "Principles of Marketing",
    "courseCode": "MKT100",
    "courseSection": "011",
    "courseDescription": "This course introduces students to the fundamental building blocks of marketing.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Marketing",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b4f",
    "courseId": "1037",
    "courseTitle": "Geometry",
    "courseCode": "MTH540",
    "courseSection": "021",
    "courseDescription": "Projective plane and 3-space. Cross-ratio, perspectivity, conics and quadrics, poles and polars.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Mathematics",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b5f",
    "courseId": "1038",
    "courseTitle": "Music and Film",
    "courseCode": "RTA180",
    "courseSection": "011",
    "courseDescription": "This course explores the relationship between music and film.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Media",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b53",
    "courseId": "1039",
    "courseTitle": "The Geography of Toronto",
    "courseCode": "GEO793",
    "courseSection": "021",
    "courseDescription": "This course provides students with an understanding of Toronto, by examining interrelated historical, social, cultural, political, and environmental issues.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Geography",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b5a",
    "courseId": "1000",
    "courseTitle": "Computer Science I",
    "courseCode": "CPS101",
    "courseSection": "011",
    "courseDescription": "This is an introduction to the basics of Computer Science",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b52",
    "courseId": "1001",
    "courseTitle": "Computer Organization I",
    "courseCode": "CPS213",
    "courseSection": "021",
    "courseDescription": "This course introduces the students to the principles and fundamentals of digital system design.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57bf3309bafd81a55b44",
    "courseId": "1002",
    "courseTitle": "Discrete Mathematics I",
    "courseCode": "MTH110",
    "courseSection": "021",
    "courseDescription": "This course covers the fundamentals of discrete mathematics with a focus on proof methods.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Mathematics",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b4b",
    "courseId": "1003",
    "courseTitle": "Physics",
    "courseCode": "PCS110",
    "courseSection": "011",
    "courseDescription": "Topics: Units and vectors. Motion - linear, projectile, circular and oscillatory motion.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Physics",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57bf3309bafd81a55b42",
    "courseId": "1004",
    "courseTitle": "The Architecture of Music",
    "courseCode": "MUS106",
    "courseSection": "011",
    "courseDescription": "this course will provide a range of technical tools for acquiring a thorough grasp of how music is organized and created.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Music",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b4d",
    "courseId": "1010",
    "courseTitle": "Communication in the Computer Industry",
    "courseCode": "CMN300",
    "courseSection": "011",
    "courseDescription": "In this workshop course, students learn to present technical information to audiences with a range of technical knowledge.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57bf3309bafd81a55b40",
    "courseId": "1011",
    "courseTitle": "Data Structures",
    "courseCode": "CPS305",
    "courseSection": "011",
    "courseDescription": "Introduction to data structures and algorithms.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b56",
    "courseId": "1012",
    "courseTitle": "Introduction to UNIX, C and C++",
    "courseCode": "CPS393",
    "courseSection": "011",
    "courseDescription": "The course introduces the UNIX operating system, and the C and C++ languages.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b4a",
    "courseId": "1013",
    "courseTitle": "Linear Algebra",
    "courseCode": "MTH108",
    "courseSection": "011",
    "courseDescription": "Systems of linear equations, matrices determinants, vectors, geometry, linear transformations.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Mathematics",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c509b3e9d1ff4c664c",
    "courseId": "1014",
    "courseTitle": "Economic History",
    "courseCode": "ECN630",
    "courseSection": "011",
    "courseDescription": "The central focus of this course is institutions and organization and how these impacted technological change and economic growth in different periods.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Economics",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57bf3309bafd81a55b43",
    "courseId": "1020",
    "courseTitle": "Database Systems I",
    "courseCode": "CPS510",
    "courseSection": "011",
    "courseDescription": "Advanced file management techniques involving fundamentals of database organization, design and management. ",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b49",
    "courseId": "1021",
    "courseTitle": "Computer Security",
    "courseCode": "CPS633",
    "courseSection": "021",
    "courseDescription": "History and examples of computer crime. Security policies and mechanisms.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
]

const transfer_courses = [
  {
    "_id": "61aa57c03309bafd81a55b51",
    "courseId": "1005",
    "courseTitle": "Computer Science II",
    "courseCode": "CPS209",
    "courseSection": "011",
    "courseDescription": "A continuation of CPS 109. Emphasis is placed on code structure, algorithm development, and Object Oriented design principles.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b48",
    "courseId": "1006",
    "courseTitle": "Computer Organization II",
    "courseCode": "CPS310",
    "courseSection": "011",
    "courseDescription": "A continuation of CPS 213. Memory; CPU architecture and instruction set; the instruction processing sequence.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57bf3309bafd81a55b41",
    "courseId": "1007",
    "courseTitle": "Social Issues, Ethics and Professionalism",
    "courseCode": "CPS412",
    "courseSection": "011",
    "courseDescription": "This course will cover some of fundamental social, legal, and ethical issues inherent in the discipline of computing.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57bf3309bafd81a55b45",
    "courseId": "1008",
    "courseTitle": "Calculus and Computational Methods I",
    "courseCode": "MTH207",
    "courseSection": "011",
    "courseDescription": "Calculus of functions of one variable and related numerical topics.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Mathematics",
    "semester": "Winter",
    "year": "2022"
  },
  {
    "_id": "61aa57c03309bafd81a55b46",
    "courseId": "1009",
    "courseTitle": "U.S. History: 1877 to the Present",
    "courseCode": "HST210",
    "courseSection": "011",
    "courseDescription": "This course surveys the period from industrialization and westward expansion in the late 19th century up to the political shifts of the present day.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "History",
    "semester": "Winter",
    "year": "2022"
  },
]

const non_related_courses = [
  {
    "_id": "61aa57c03309bafd81a55b61",
    "courseId": "1031",
    "courseTitle": "Software Project Management",
    "courseCode": "CPS714",
    "courseSection": "011",
    "courseDescription": "Introduction to issues involved in managing large, complex software projects. ",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b57",
    "courseId": "1032",
    "courseTitle": "Machine Learning",
    "courseCode": "CPS803",
    "courseSection": "011",
    "courseDescription": "This course develops an aptitude for applying machine learning algorithms to different problem domains.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Computer Science",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b58",
    "courseId": "1033",
    "courseTitle": "Energy, Earth and Ecosystems",
    "courseCode": "GEO131",
    "courseSection": "011",
    "courseDescription": "This course takes a systems-based approach to understanding the dynamics of Planet Earth and how humans interact with it.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Geography",
    "semester": "Fall",
    "year": "2021"
  },
  {
    "_id": "61aa57c03309bafd81a55b4c",
    "courseId": "1034",
    "courseTitle": "Philosophy and Literature",
    "courseCode": "PHL648",
    "courseSection": "011",
    "courseDescription": "This course explores some of the rich points of intersection between philosophy and literature.",
    "courseCredits": "1",
    "durationHours": "60",
    "department": "Philosophy",
    "semester": "Fall",
    "year": "2021"
  }
]

module.exports = {
  calendar: calendar,
  fulfilled_courses: fulfilled_courses,
  transfer_courses: transfer_courses,
  non_related_courses: non_related_courses,
};